### ISSUE TITLE
Crash using coloredlogs

### ISSUE THREAD

**Issue by isaacda** [microsoft/picologging#159]
I have been using the `coloredlogs` module with the Python `logging` module with success. I needed a faster logger, so I swapped in   `picologging`. However this caused a crash. Below is a code snip that causes the crash. I am using `picologging/0.9.1` and `coloredlogs/15.0.1`.

```python
# Fails using picologging module
import picologging as logging   
print(f"picologging.__version__: {logging.__version__}")

# Works using logging module
#import logging                
#print(f"logging.__version__: {logging.__version__}")

import coloredlogs
print(f"coloredlogs.__version__: {coloredlogs.__version__}")

# Setup colored logger
logger = logging.getLogger()
logger.addHandler(logging.StreamHandler())
coloredlogs.install(logger=logger, level="INFO")

logger.info("Info message")
logger.warning("Warning message")
logger.error("Error message")
logger.critical("Critical message")
```

The traceback/message dump follows.

```
--- Logging error ---
Traceback (most recent call last):
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\logging\__init__.py", line 1085, in emit
    msg = self.format(record)
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\logging\__init__.py", line 929, in format
    return fmt.format(record)
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\site-packages\coloredlogs\__init__.py", line 1135, in format
    copy.__class__ = record.__class__
TypeError: __class__ assignment only supported for heap types or ModuleType subclasses
Call stack:
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\site-packages\traitlets\config\application.py", line 1043, in launch_instance
    app.start()
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\site-packages\ipykernel\kernelapp.py", line 736, in start
    self.io_loop.start()
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\site-packages\ipykernel\kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell
    await result
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\site-packages\ipykernel\kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\site-packages\ipykernel\zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\site-packages\IPython\core\interactiveshell.py", line 3009, in run_cell
    result = self._run_cell(
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\site-packages\IPython\core\interactiveshell.py", line 3064, in _run_cell
    result = runner(coro)
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\site-packages\IPython\core\interactiveshell.py", line 3269, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\site-packages\IPython\core\interactiveshell.py", line 3448, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\ProgramData\Anaconda2021_05\envs\blast-dev\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\isaacda\AppData\Local\Temp\ipykernel_26356\21207353.py", line 20, in <module>
    logger.critical("Critical message")
Message: 'Critical message'
Arguments: ()
```

Thanks!

**Comment by tonybaloney** [comment]
This issue is fixed for the latest release (0.9.3)
